# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06027771944e2093f6fccaa58b2451da801436360041e6ab930ee27b7524f869fc297ecfacdeb076879877e10aa0bad79e6af0a9d0afd0864a98a20c0f5aa732

test:
  secret_key_base: 1658a2e6ad9670c8363800f472e353dd0d801245510ecd5c1d248d13ebb66f44ea3f818997235dd4b7e625a118a50acb3b2c71ef5bb08849f398ed9b2fdc129e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

cetic:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
